# Generated by Django 5.2.6 on 2025-09-21 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleddata',
            name='linked_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawled_records', to='api.restaurant'),
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='linked_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawled_records', to='api.review'),
        ),
    ]
