# Generated by Django 5.2.6 on 2025-12-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_prefix_indexes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantReview',
        ),
    ]
