# Generated by Django 5.2.6 on 2025-09-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleddata',
            name='status',
            field=models.CharField(choices=[('Pending', 'Đang chờ xử lý'), ('Processed', 'Đã xử lý'), ('Error', 'Bị lỗi')], default='Pending', max_length=20),
        ),
    ]
