# Generated by Django 5.2.6 on 2025-09-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='detail_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
