# Generated by Django 5.2.6 on 2025-10-07 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_restaurant_detail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawleddata',
            name='linked_review',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('Report', 'Report Issue / Error'), ('Suggestion', 'Feature Suggestion'), ('General', 'General Feedback')], default='General', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
