# Generated by Django 5.2.6 on 2025-10-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_crawleddata_linked_review_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='vector_id',
        ),
    ]
