# Generated by Django 5.2.6 on 2025-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_restaurant_vector_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='message_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
