# Generated by Django 5.2.6 on 2025-11-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_searchhistory_user_feedback_message_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawleddata',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crawleddata',
            name='url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='crawledsource',
            name='base_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crawledsource',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rag_context_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='crawleddata',
            table='CrawledData',
        ),
        migrations.AlterModelTable(
            name='crawledsource',
            table='CrawledSource',
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='Favorites',
        ),
        migrations.AlterModelTable(
            name='foodjourney',
            table='FoodJourney',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='Restaurants',
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_review_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_language', models.CharField(default='vi', max_length=10)),
                ('review_time', models.DateTimeField(blank=True, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.restaurant')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.crawledsource')),
            ],
            options={
                'db_table': 'RestaurantReviews',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSourceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('last_review_time', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_stats', to='api.restaurant')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_stats', to='api.crawledsource')),
            ],
            options={
                'db_table': 'RestaurantSourceStats',
                'unique_together': {('restaurant', 'source')},
            },
        ),
    ]
