# Generated by Django 5.2.6 on 2025-11-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='ResetToken',
        ),
    ]
